apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # necessary for Kustomize identification
  labels:
    env: prod
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
